### ISSUE TITLE
role name instead of capability checks

### ISSUE THREAD

**Issue by danmarsden** [vfremaux/moodle-block_shop_course_seats#5]
https://github.com/vfremaux/moodle-block_shop_course_seats/blob/master/manage.php#L123

sites change the names of roles and use custom roles all the time - it would be better for you to check capablities here

**Comment by vfremaux** [comment]
this is not a role check. We need to find one role that can match the "supervisor" riole if it was not configured. Standard teacher role is the best choice for that. This is needed because a product will have to enrol some users as result of the purchase, or some post-purchase life-cycle activation. Usually the required role for product "supervision" is defined in the product production metadata when the product is configured in the shop. This may not be done by the shop administrators on a quick setup. This will be the default used role if the product requires supervision.

**Comment by vfremaux** [comment]
Not retained.

**Comment by danmarsden** [comment]
it might be an idea to add some comments to the code there in case this goes through another organisations review process to help a future review. I also wonder if you need to add some further validation code here...

what happens if $productinfo->supervisor) is empty and the site has changed the shortname of the "teacher" role or deleted it? - does your code fall over?

you might want to check if $supervisorrole is still empty after trying to get it from $productinfo->supervisor and "teacher"
